### ISSUE TITLE
安装部署问题

### ISSUE THREAD

**Issue by Jackson-cj** [fate-ubw/RAGLAB#7]
Pip subprocess error:
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-jlp3hfti/deepspeed_edffb43e939646099dd2f063ff68d5e1/setup.py", line 100, in <module>
          cuda_major_ver, cuda_minor_ver = installed_cuda_version()
        File "/tmp/pip-install-jlp3hfti/deepspeed_edffb43e939646099dd2f063ff68d5e1/op_builder/builder.py", line 50, in installed_cuda_version
          raise MissingCUDAException("CUDA_HOME does not exist, unable to compile CUDA op(s)")
      op_builder.builder.MissingCUDAException: CUDA_HOME does not exist, unable to compile CUDA op(s)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
                                                                                    failed

CondaEnvException: Pip failed

**Comment by Jackson-cj** [comment]
请问一下是什么问题

**Comment by fate-ubw** [comment]
请问您是否可以提供一下 input 的命令和 output 的全部结果，按照我的理解应该是某个 lib 需要的 cuda 版本和您环境的 cuda 版本不一致导致的，但是如果需要定位还需要您提供 input 的命令，这样我可以更好的帮助您解决问题～

**Comment by fate-ubw** [comment]
您好~请问您解决了吗，如果还没有解决，欢迎积极提问，我非常愿意帮助你解决issue

**Comment by Jackson-cj** [comment]
> 您好~请问您解决了吗，如果还没有解决，欢迎积极提问，我非常愿意帮助你解决issue
安装部署解决了，请问一下有更详细的使用教程和开发教程吗？小白在学习当中。

**Comment by fate-ubw** [comment]
您好，这个 lib 主要是提供算法的复现和公平比较的实验平台，如果想要学习或者开发，我建议最简单的方法就是从最简单的算法开始每个算法都 debug 一遍，大概的学习路径是这样的：
1. 学习 pdb 的使用方法，原因更好的帮助你 debug 算法，理解算法
2. 运行 naive rag 的算法流程，并且使用 pdb debug 一遍，了解关键的环节是什么样子的，注意如果你只是想了解算法的流程其实并不需要reproduce exp results。 只需要跑 interact mode 即可，因为这个是专门为初学者学使用的，不涉及评估，另外当初设计的时候就是为了可以帮助到初学者，因此开源了所有的 yaml 文件和 bash 文件，你可以直接运行 run 文件夹下面的 bash 文件来执行对应的程序
3. 在此基础上学习 advanced rag 算法的流程，因为这些算法都是继承 naive rag 算法，可以同时参考论文和代码，对比这来学习
4. 开发新的算法，开发过程其实只需要参考其他算法即可，最关键的就是继承 naive rag 算法
祝顺利～如果还有什么其他问题欢迎提问，我会积极帮助你解决问题 🤗

**Comment by Jackson-cj** [comment]
> 您好，这个 lib 主要是提供算法的复现和公平比较的实验平台，如果想要学习或者开发，我建议最简单的方法就是从最简单的算法开始每个算法都 debug 一遍，大概的学习路径是这样的：
> 
>     1. 学习 pdb 的使用方法，原因更好的帮助你 debug 算法，理解算法
> 
>     2. 运行 naive rag 的算法流程，并且使用 pdb debug 一遍，了解关键的环节是什么样子的，注意如果你只是想了解算法的流程其实并不需要reproduce exp results。 只需要跑 interact mode 即可，因为这个是专门为初学者学使用的，不涉及评估，另外当初设计的时候就是为了可以帮助到初学者，因此开源了所有的 yaml 文件和 bash 文件，你可以直接运行 run 文件夹下面的 bash 文件来执行对应的程序
> 
>     3. 在此基础上学习 advanced rag 算法的流程，因为这些算法都是继承 naive rag 算法，可以同时参考论文和代码，对比这来学习
> 
>     4. 开发新的算法，开发过程其实只需要参考其他算法即可，最关键的就是继承 naive rag 算法
>        祝顺利～如果还有什么其他问题欢迎提问，我会积极帮助你解决问题 🤗

好的，十分感谢 🤗

**Comment by fate-ubw** [comment]
I'll close this issue, and if you have any other questions, feel free to reopen it~
